
def create_few_shot_dataset(dataframe, samples_per_category=5):
    """
    Creates a few-shot dataset by sampling a specified number of examples from each category.
    
    Parameters:
    - dataframe (pd.DataFrame): DataFrame containing 'category' and 'text' columns.
    - samples_per_category (int): Number of samples to select from each category.
    
    Returns:
    - pd.DataFrame: A new DataFrame containing the few-shot dataset.
    """
    few_shot_data = []

    categories = dataframe['category'].unique()
    for category in categories:
        # Select samples_per_category examples for the category
        sampled_data = dataframe[dataframe['category'] == category].sample(samples_per_category, random_state=42)
        few_shot_data.append(sampled_data)
    
    few_shot_dataset = pd.concat(few_shot_data).reset_index(drop=True)
    return few_shot_dataset

few_shot_df = create_few_shot_dataset(df, samples_per_category=5)

few_shot_output_path = "/kaggle/working/few_shot_dataset.csv"
few_shot_df.to_csv(few_shot_output_path, index=False)

print(f"Few-shot dataset saved to {few_shot_output_path}")
category                                               text
0        politics  Kennedy to make temple address\n\nCharles Kenn...
1        politics  UK plan to deport terror suspects\n\nDeals are...
2        politics  Lib Dems' 'bold' election policy\n\nCharles Ke...
3        politics  Choose hope over fear - Kennedy\n\nVoters will...
4        politics  Butler launches attack on Blair\n\nFormer civi...
5           sport  Sella wants Michalak recall\n\nFormer France c...
6           sport  O'Driscoll saves Irish blushes\n\nTwo moments ...
7           sport  Fit-again Betsen in France squad\n\nFrance hav...
8           sport  Newry to fight cup exit in courts\n\nNewry Cit...
9           sport  Sprinter Walker quits athletics\n\nFormer Euro...
10           tech  Court mulls file-sharing future\n\nJudges at t...
11           tech  Camera phones are 'must-haves'\n\nFour times m...
12           tech  Seamen sail into biometric future\n\nThe luxur...
13           tech  Sony PSP tipped as a 'must-have'\n\nSony's Pla...
14           tech  Speech takes on search engines\n\nA Scottish f...
15  entertainment  Foxx and Swank win US awards\n\nJamie Foxx and...
16  entertainment  U2 stars enter rock Hall of Fame\n\nSinger Bru...
17  entertainment  'My memories of Marley...'\n\nTo mark the 60th...
18  entertainment  Berlin cheers for anti-Nazi film\n\nA German m...
19  entertainment  Help for indies in download sales\n\nA campaig...
20       business  Khodorkovsky quits Yukos shares\n\nJailed tyco...
21       business  EU-US seeking deal on air dispute\n\nThe EU an...
22       business  US economy still growing says Fed\n\nMost area...
23       business  BT offers equal access to rivals\n\nBT has mov...
24       business  US trade gap ballooned in October\n\nThe US tr...
